on:
  push:
    paths:
      - README.Rmd
  pull_request:
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown", "fitzRoy", "tidyverse"))' 
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git config --global user.name 'James Day'
          git config --global user.email '17557361+jimmyday12@users.noreply.github.com'
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push || echo "No changes to commit"
